spring:
  datasource:
    url: jdbc:postgresql://localhost:5437/inventory
    username: administrator
    password: administrator123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB
server:
  port: 8086
grpc:
  server:
    port: 9090
inventory:
  documents:
    base-path: ${INVENTORY_DOCS_PATH:./Documents/consumptions}