server:
  port: 8082
spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/companies
    username: administrator
    password: administrator123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true